export const eventsData = [
    {
        imgSrc:"/Images/EventImages/ajit.png",
        width:"300",
        height:"300",
        link:"https://www.instagram.com/p/Cw0zfffBkGu/"
    },
    {
        imgSrc:"/Images/EventImages/jay.png",
        width:"300",
        height:"300",
        link:"https://www.instagram.com/p/CwvRhQhvMqf/"
    },
    {
        imgSrc:"/Images/EventImages/suneja.jpg",
        width:"300",
        height:"300",
        link:"https://www.instagram.com/p/Cv-ADc7Pn0C/"
    },
    {
        imgSrc:"/Images/EventImages/vivek.webp",
        width:"300",
        height:"300",
        link:"https://www.instagram.com/p/CwJuaOQIsam/"
    },
]