
import './globals.css'
import { Inter } from 'next/font/google';
import { AboutUs } from '@/components/AboutUs';

import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HackOdisha 3.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      
      <AboutUs/>

    </html>
  );
}
// <body className={inter.className}>{children}</body> 