import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "../components/Footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HackOdisha 3.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
